### ISSUE TITLE
How to register a partner?

### ISSUE THREAD

**Issue by jch** [nixme/pandora_client#4]
The README hints that I need a partner login in order to access the API. How does one register as a partner? Googling didn't yield anything useful.

``` ruby
Pandora::Partner.new(username, password, device, encryption_key, decryption_key)
```

Thanks for the gem!

**Comment by dphaener** [comment]
Hey not sure if anyone has replied, but you can find the partner
information here: http://pan-do-ra-api.wikia.com/wiki/Json/5/partners
That wiki has a ton of information on how to interact with the api. I use
the android partner login for my desktop app, but you can use anything that
doesn't require a pandora one account (if you want to use the free version
that is). Hope that helps!

Darin

**Comment by jch** [comment]
@dphaener :metal: thank you so much!
